remove futures if not already removed (#219)
Customer reported seeing a few cases where we try to cleanup a future
from our queue when it doesn't exist
```
[Statsig]: An unexpected error occurred.
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/statsig/statsig_logger.py", line 204, in _periodic_flush
    self._flush_futures()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/statsig/statsig_logger.py", line 196, in _flush_futures
    self._futures.remove(future)
ValueError: deque.remove(x): x not in deque
```

Not sure what is the exact cause in this case but this could occur if
the logging interval is set too low and multiple wait conditions are
handling the same future. It shouldn't affect the execution of the
future itself, but will cause a race condition on the queue cleanup